config/routes.rb
Glatos::Application.routes.draw do

  root :to => 'home#index'
  match '/about' => 'home#about', :as => :about, :via => :get
  match '/acoustic_telemetry' => 'home#acoustic_telemetry', :as => :acoustic_telemetry, :via => :get
  match '/have_data' => 'home#have_data', :as => :have_data, :via => :get

  devise_for :users

  resources :users, :only => [:index, :destroy, :update]
  match 'users/newsletter' => 'users#newsletter', :as => :user_newsletter, :via => :get

  resources :reports, :only => [:index, :new, :create, :destroy, :update, :show]

  resources :deployments, :only => [:index, :destroy]

  resources :submissions, :only => [:new, :create, :show, :index, :destroy] do
    member do
      get 'analyze'
      get 'parse'
      get 'deployments'
      get 'proposed'
      get 'retrievals'
      get 'tags'
      get 'locations'
      get 'project'
    end
  end

  # The projects controller is identical to the studies
  resources :studies, :projects, :controller => :studies, :only => [:index, :show, :edit, :update] do
    resources :deployments, :only => [:index, :destroy]
    resources :reports, :only => [:index, :destroy, :update]
  end

  match 'explore' => 'explore#index', :as => :explore, :via => :get
  match 'search' => 'search#index', :as => :search, :via => :get
  match 'search/tags' => 'search#tags', :as => :search_tags, :via => :get
  match 'search/reports' => 'search#reports', :as => :search_reports, :via => :get
  match 'search/studies' => 'search#studies', :as => :search_studies, :via => :get
  match 'search/deployments' => 'search#deployments', :as => :search_deployments, :via => :get
  match 'search/tag' => 'search#tag', :as => :tag_search, :via => :get
  match 'search/match_tags' => 'search#match_tags', :as => :multi_tag_search, :via => :get

  match 'static/:action' => 'static#:action', :as => :static, :via => :get

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  layout 'search'

  def index

  end

  def tag
    authorize! :manage, Tag
  end

  def match_tags
    z_tags = params[:text].split(",").map(&:strip)

    tags_match = Tag.exact_match(z_tags.join(" ")).map(&:id)
    deps_match = TagDeployment.includes(:tag).exact_match(z_tags).map{ |td| td.tag.id }
    ids_match = z_tags.map{ |z| Tag.find_all_matches(z).map(&:id) }

    ids = (tags_match + deps_match + ids_match).uniq

    tags = Tag.includes({:active_deployment => {:study => :user}}).where(:id => ids)

    # TODO: Do we need only return tags the user can manage?
    # tags.select! { |t| can? :manage, t }
    render :json => tags.as_json({
                      :only => [:id, :code, :code_space, :model],
                      :methods => [:active_deployment_json]
                      })
  end

  def tags
    tags = Tag.includes({:tag_deployments => :study}).search_all(params[:text])
    deps = TagDeployment.includes(:tag).includes(:study).search_all(params[:text]).map(&:tag)
    tags = (tags + deps).select { |t| can? :manage, t }
    render :json => tags.as_json({
                      :only => [:id, :code, :code_space],
                      :methods => [:active_deployment_json]
                    })
  end

  def reports
    reports = Report.inclues(:tag).includes({:tag_deployment => :study}).search_all(params[:text])
    render :json => reports.as_json({
                      :include => [
                        {:tag => {
                          :only => [:id,:code]
                        }},

                        {:tag_deployment => {
                          :only => [nil],
                          :include => 
                            {:study => {
                              :only => [:id, :name]
                            }}
                        }}
                      ]
                    })
  end

  def studies
    studies = Study.search_all(params[:text])
    render :json => studies.as_json({

    })
  end

  def deployments
    deps = Deployment.includes(:study, :otn_array).search_all(params[:text])
    render :json => deps.as_json({
                      :only => [:id, :start, :ending, :seasonal, :model],
                      :methods => [:code],
                      :include => {
                        :study => { :only => [:id, :name] },
                        :otn_array => { :only => :name }
                      }
                    })
  end

end

app/views/search/index.html.haml
%h2
  Search

%p Enter a search term to query Projects in the GLATOSWeb system.

%textarea{:class => 'tags_input'}

%button{:class => 'searcher'} Search

- if can? :manage, Tag
  Looking for the
  = link_to("tag search?", tag_search_path)

.clear

%span{:style => 'font-size: 80%; font-weight: bold;'}
  Examples: Sturgeon (species), "St Marys River" (location), Holbrook (investigator)

#search_tables{:style => 'display: none;'}
  .search_table{:class => "two_wide"}
    %h3 Studies
    %h5{:id => 'study_count'}
    %div{:id => 'studies'}
  -#
    .search_table{:class => "two_wide_last"}
      %h3 Deployments
      %h5{:id => 'deployment_count'}
      %div{:id => 'deployments'}
.clear

:javascript

  function buildRow(label, value) {
    var text = "";
    text += "<tr>";
      text += "<td class='label'>";
        text += label
      text += "</td>";
      text += "<td>";
        text += value;
      text += "</td>";
    text += "</tr>";
    return text;
  }

  function buildStudyBox(val) {
    text = "";
    text += "<div class='info'>";
      text += "<h4>";
        text += "<a href='#{root_url}projects/" + val.id + "'>" + val.name + "</a>";
      text += "</h4>";

      // TABLE
      text += "<table>";
        text += "<tbody>";
          text += buildRow("Species", val.species);
          text += buildRow("Title", val.title);
        text += "</tbody>";
      text += "</table>";

    text += "</div>";
    return text;
  }

  function buildDeploymentBox(val) {
    text = "";
    text += "<div class='info'>";
      text += "<h4>" + val.code + "</h4>";

      // TABLE
      text += "<table>";
        text += "<tbody>";
          text += buildRow("Model", val.model);
          text += buildRow("Study", "<a href='#{root_url}/projects/" + val.study.id + "'>" + val.study.name + "</a></li>");
        text += "</tbody>";
      text += "</table>";

    text += "</div>";
    return text;
  }

  $(document).ready(function() {

    $(".searcher").click(function(e) {
      e.preventDefault();

      var phrase = $(".tags_input").val();

      $.ajax({
        type: "GET",
        url: "#{search_deployments_path({:format => :js})}",
        data: "text="+phrase,
        dataType: 'json',
        success: function(data){
          var items = [];
          $("#deployment_count").html(data.length + " results")
          $.each(data, function(key, val) {
            items.push(buildDeploymentBox(val));
          });
          $("#deployments").html(items.join(''));
        },
        error: function(){
          $("#deployment_count").html("There was a problem retreiving any matching Deployments");
        }
      });

      $.ajax({
        type: "GET",
        url: "#{search_studies_path({:format => :js})}",
        data: "text="+phrase,
        dataType: 'json',
        success: function(data){
          var items = [];
          $("#study_count").html(data.length + " results")
          $.each(data, function(key, val) {
            items.push(buildStudyBox(val));
          });
          $("#studies").html(items.join(''));
          $('#search_tables').show();
        },
        error: function(){
          $("#study_count").html("There was a problem retreiving any matching Studies");
          $('#search_tables').show();
        }
      });

    });

  });

app/views/search/tag.html.haml
%h2
  Search for Tags

%p Enter tags you would like to search, one per line.  These can be both internal and external tags.

%textarea{:class => 'tags_input'}

%button{:class => 'searcher'} Search
Looking for the 
= link_to("project search?", search_path)

.clear

%span{:style => 'font-size: 80%; font-weight: bold;'}
  Example:
  .search_hint_list
    A69-9002-4807 (full code space)
    %br
    31942 (internal tag)
    %br
    4257 (external tag)

#search_tag_table
  %h5{:id => 'tag_count'}

#table_contents{:style => 'display: none;'}

  #done{:style => "padding: 20px;"}
    #choices
    .clear

  .clear

  %table{:id => :table}

:javascript

  function makeStudyLink(oObj) {
    var text = "<a href='" + getStudyLink(oObj) + "' target='_blank'>Link</a>";
    return text;
  }

  function getStudyLink(oObj) {
    var text = "#{root_url}" + "projects/" + oObj.aData.active_deployment_json.study.id;
    return text;
  }

  function getFullName(oObj) {
    var text = oObj.aData.active_deployment_json.study.user.name + " (" + oObj.aData.active_deployment_json.study.user.email + ")";
    return text;
  }

  $(document).ready(function() {

    $(".searcher").click(function(e) {
      e.preventDefault();

      $('#table').dataTable().fnClearTable();

      var phrase = $(".tags_input").val().split(/\n/).join(",");

      $.ajax({
        type: "GET",
        url: "#{multi_tag_search_path({:format => :js})}",
        data: "text="+phrase,
        dataType: 'json',
        success: function(data){
          var items = [];
          $("#tag_count").html(data.length + " results")
          var count = 1;

          $('#table').dataTable().fnAddData(data);
          $('#table_contents').show();
          oTableTools.fnResizeButtons();
        },
        error: function(){
          $("#tag_count").html("There was a problem with your search.  Please try again.")
        }
      });

    });

    var oTable = $('#table').dataTable({
      "sPaginationType": "full_numbers",
      "oLanguage": {
        "sSearch": "Filter Results:"
      },
      "aoColumns": [
        { "sTitle": "Project", "sName": "project", "mDataProp": "active_deployment_json.study.name" },
        { "sTitle": "Code Space", "sName": "code_space", "mDataProp": "code_space" },
        { "sTitle": "Code", "sName": "code", "mDataProp": "code" },
        { "sTitle": "External Codes", "sName": "external_codes", "mDataProp": "active_deployment_json.external_codes" },
        { "sTitle": "Species", "sName": "common_name", "mDataProp": "active_deployment_json.common_name" },
        { "sTitle": "Release Location", "sName": "release_location", "mDataProp": "active_deployment_json.release_location" },
        { "sTitle": "Investigator", "sName": "pi", "mDataProp": "active_deployment_json.study.user.name",
          "fnCellRender": function (oObj){ return getFullName(oObj); },
          "fnRender": function (oObj){ return getFullName(oObj); },},
        { "sTitle": "Project Page", "sName": "site", "mDataProp": null, "bSortable": false,
          "fnCellRender": function (oObj){ return getStudyLink(oObj); },
          "fnRender": function (oObj){ return makeStudyLink(oObj); },
        }
      ]
    });

    var oTableTools = new TableTools( oTable, {
      "sSwfPath": "#{image_path 'copy_csv_xls_pdf.swf'}",
    });
    
    $('#choices').after( oTableTools.dom.container );

  });