config/routes.rb
Glatos::Application.routes.draw do

  root :to => 'home#index'
  match '/about' => 'home#about', :as => :about, :via => :get
  match '/acoustic_telemetry' => 'home#acoustic_telemetry', :as => :acoustic_telemetry, :via => :get
  match '/have_data' => 'home#have_data', :as => :have_data, :via => :get

  devise_for :users

  resources :users, :only => [:index, :destroy, :update]
  match 'users/newsletter' => 'users#newsletter', :as => :user_newsletter, :via => :get

  resources :reports, :only => [:index, :new, :create, :destroy, :update, :show]

  resources :deployments, :only => [:index, :destroy]

  resources :submissions, :only => [:new, :create, :show, :index, :destroy] do
    member do
      get 'analyze'
      get 'parse'
      get 'deployments'
      get 'proposed'
      get 'retrievals'
      get 'tags'
      get 'locations'
      get 'project'
    end
  end

  # The projects controller is identical to the studies
  resources :studies, :projects, :controller => :studies, :only => [:index, :show, :edit, :update] do
    resources :deployments, :only => [:index, :destroy]
    resources :reports, :only => [:index, :destroy, :update]
  end

  match 'explore' => 'explore#index', :as => :explore, :via => :get
  match 'search' => 'search#index', :as => :search, :via => :get
  match 'search/tags' => 'search#tags', :as => :search_tags, :via => :get
  match 'search/reports' => 'search#reports', :as => :search_reports, :via => :get
  match 'search/studies' => 'search#studies', :as => :search_studies, :via => :get
  match 'search/deployments' => 'search#deployments', :as => :search_deployments, :via => :get
  match 'search/tag' => 'search#tag', :as => :tag_search, :via => :get
  match 'search/match_tags' => 'search#match_tags', :as => :multi_tag_search, :via => :get

  match 'static/:action' => 'static#:action', :as => :static, :via => :get

end

app/controllers/home_controller.rb
class HomeController < ActionController::Base

  layout 'home'

  def index
  end

  def about
    @studies = Study.select([:id,:code,:name]).select do |s|
      s.active || (authorize! :update, s rescue false)
    end
    render :layout => 'application'
  end

  def acoustic_telemetry
    render :layout => 'application'
  end

  def have_data
    render :layout => 'application'
  end

end

app/views/home/about.html.haml
#about_page

  #about_left

    %h2
      What is GLATOS?

    %p
      The Great Lakes Acoustic Telemetry Observation System (GLATOS) is a network of researchers conducting acoustic telemetry projects on fish movement in the Laurentian Great Lakes.  GLATOS provides these researchers with opportunities to develop partnerships and share fish detection data among projects.


  #about_right
    %div{:class => 'info'}
      %h2 GLATOS Projects:
      %ul{:class => 'project_list'}

        - @studies.each do |s|
          %li
            = link_to "#{s.name} (#{s.code})", project_path(s.id)
  .clear

  %h2 GLATOS Mission Statement
  %p
    GLATOS aims to:

  %ol{:class => 'mission'}
    %li
      1. Build a network of researchers conducting acoustic telemetry studies within the Great Lakes Basin.
    %li
      2. Foster the development of partnerships and cooperative project planning through GLATOSWeb.
    %li
      3. Extend the effective range of individual studies by providing a mechanism to share detection data among projects.

  %p
    GLATOS is administered by the Great Lakes Fishery Commission, in partnership with the Great Lakes Observation System, and the U.S. Geological Survey and supported by the Great Lakes Restoration Initiative.  The GLATOS mission is accomplished through two tools:  #{link_to 'GLATOSWeb', root_path}  and GLATOSLink.


  %h2
    Questions?  Contact:

  %p
    Charles Krueger
    %br
    Michigan State University
    %br
    Phone:  734-417-8014
    %br
    Email:  kruege62@msu.edu

  %p
    Jessica Ives
    %br
    Great Lakes Fishery Commission
    %br
    Phone:  734-669-3020
    %br
    Email:  jives@glfc.org

app/views/home/acoustic_telemetry.html.haml
#acoustic_telemetry

  %h2
    What is acoustic telemetry?

  %ul
    %li
      %span{:class => 'headtitle'}
        Acoustic:
      relating to sound
    %li
      %span{:class => 'headtitle'}
        Telemetry:
      measurement from a distance

  %p
    Researchers use acoustic telemetry to collect information about fish movements (e.g., migration patterns, habitat use, survival).  An acoustic telemetry system consists of two main components:  #{link_to 'transmitters', '#transmitters'} and #{link_to 'receivers', '#receivers'}.

  %p{:id => 'transmitters'}
    %strong
      Transmitters 
    are electronic tags that broadcast a series of “pings” (sound pulses) into the surrounding water.  Tags are either surgically implanted or attached externally to a fish of interest so that once released into the wild, a tagged fish can be “heard” by any receiver within range.  The range can vary from a few meters to more than a kilometer.   The signal typically transmits once every minute or two.

  %p{:id => 'receivers'}
    %strong
      Receivers
    are small, data-logging computers anchored near the bottom of a lake or stream or the ocean that “listen” for tagged fish.  When a signal is identified, the tag’s unique ID code is saved with the date and time.  The data from any single receiver provide a record of each visit to that location by a tagged fish.  Researchers often deploy many receivers over large regions to understand the movement patterns of tagged fish.

  #{image_tag 'actel.png'}

  %br
  %br
  %br
  %h2
    Beyond Presence-Absence

  %p
    %strong
      Sensor Tags:
    Some transmitters incorporate sensors that monitor biological and/or environmental information that is transmitted along with ID code. The most common sensors are: pressure (for determining depth), temperature, and acceleration (for monitoring swimming behavior). These sensors allow researchers to remotely monitor both the internal and external environment of fishes, allowing them to address biological questions that were previously difficult (or impossible) to answer.
  %p
    %strong
      Fine-Scale Positioning:
    A major advancement in acoustic telemetry is the ability to fine-scale position fishes using an array of closely located receivers. While the detection range for a presence-absence telemetry array can be more than a kilometer, positional arrays can position fish to within a few meters of their true location. Like GPS technology, a positional array uses the difference in time it takes for a signal to be “heard” by three or more receivers to “triangulate” the position of a fish.  The resulting fish “tracks” can provide new insights into fish behavior.

app/views/home/have_data.html.haml
#have_data

  %h2
    Have Data?

  %p
    Are you a researcher conducting acoustic telemetry studies within the Laurentian Great Lakes Basin?  Are you ready to submit data about receiver locations (past, present, or future), or transmitters?  GLATOSWeb wants you!

  %p
    - if can? :create, Submission
      %strong
        Last updated: Tuesday, May 22nd, 2012
      %br
      = link_to "Download", static_path("GLATOSWeb_Submission_Package.zip"), :target => '_blank'
      your GLATOSWeb Data Submittal Package
      %br
      %br
      = link_to "Submit", new_submission_path
      your completed GLATOSWeb Data Submittal Package
    - else
      The first step is to register as an Investigator
      = link_to "here.", new_user_registration_path
      Once your registration is approved, a link will appear on this page to download the GLATOSWeb Data Submittal Package.

  %p
    The GLATOSWeb Data Submittal Package contains templates for the entry of project information, proposed receiver deployments, actual receiver locations, and transmitter/tag details. The package, a compressed .ZIP archive, also contains descriptions of necessary and recommended data and instructions for entering information into the templates and for submittal of the formatted information to GLATOSWeb.

  %p
    Please direct questions about data submittal to
    = link_to "GLATOSWeb@glfc.org", "mailto:GLATOSWeb@glfc.org"

app/views/home/index.html.haml
#container
  #background

    #information
      .test-link #{link_to "Click here to preview our new website", 'http://52.10.20.63/'}

      %p
        GLATOSWeb compiles acoustic telemetry project information and helps users learn more about ongoing acoustic telemetry projects in the Great Lakes.  Scientists have been implanting Great Lakes fish with transmitters and, like the GPS on a car, have been tracking fish movement through a network of receivers placed on the bottom of the lakes.  The purpose of GLATOS is to help scientists and the public learn more about Great Lakes acoustic telemetry projects and their contribution to research.

    #links
      %ul
        %li
          #{link_to "What is Acoustic Telemetry?", acoustic_telemetry_path}
        %li
          #{link_to "About GLATOS", about_path}
        %li
          #{link_to "Have Data?", have_data_path}

    #functions
      .box{:class => 'globe'}
        .globelink
          #{link_to "EXPLORE", explore_path}
        %p
          Explore a map of GLATOS projects.

      .box{:class => 'search'}
        .searchlink
          #{link_to "SEARCH", search_path}
        %p
          Search the GLATOS database by keyword.

      .box{:class => 'found'}
        .foundlink
          #{link_to "FOUND A TAG?", new_report_path}
        %p
          %span
            Reward!
          Click here for instructions on what to do next.

    #footer
      .left_images
        .top_img
          = link_to image_tag(asset_path('glr.png')), "http://greatlakesrestoration.us/"
        .bottom_img
          .left_img
            = link_to image_tag(asset_path('glfc_logo.png')), "http://glfc.org"
          .right_img
            = link_to image_tag(asset_path('glos_logo.png')), "http://glos.us"

      .login

        #flashes
          - flash.each do |name, msg|
            = content_tag :p, msg, :class => "flasher #{name}" if msg.is_a?(String)

        - if current_user
          = link_to('Logout', destroy_user_session_path, :method => :get)
        - else
          = link_to('Login or Register to Join the GLATOS Network', new_user_session_path, :class => 'login_home_button')