config/routes.rb
Glatos::Application.routes.draw do

  root :to => 'home#index'
  match '/about' => 'home#about', :as => :about, :via => :get
  match '/acoustic_telemetry' => 'home#acoustic_telemetry', :as => :acoustic_telemetry, :via => :get
  match '/have_data' => 'home#have_data', :as => :have_data, :via => :get

  devise_for :users

  resources :users, :only => [:index, :destroy, :update]
  match 'users/newsletter' => 'users#newsletter', :as => :user_newsletter, :via => :get

  resources :reports, :only => [:index, :new, :create, :destroy, :update, :show]

  resources :deployments, :only => [:index, :destroy]

  resources :submissions, :only => [:new, :create, :show, :index, :destroy] do
    member do
      get 'analyze'
      get 'parse'
      get 'deployments'
      get 'proposed'
      get 'retrievals'
      get 'tags'
      get 'locations'
      get 'project'
    end
  end

  # The projects controller is identical to the studies
  resources :studies, :projects, :controller => :studies, :only => [:index, :show, :edit, :update] do
    resources :deployments, :only => [:index, :destroy]
    resources :reports, :only => [:index, :destroy, :update]
  end

  match 'explore' => 'explore#index', :as => :explore, :via => :get
  match 'search' => 'search#index', :as => :search, :via => :get
  match 'search/tags' => 'search#tags', :as => :search_tags, :via => :get
  match 'search/reports' => 'search#reports', :as => :search_reports, :via => :get
  match 'search/studies' => 'search#studies', :as => :search_studies, :via => :get
  match 'search/deployments' => 'search#deployments', :as => :search_deployments, :via => :get
  match 'search/tag' => 'search#tag', :as => :tag_search, :via => :get
  match 'search/match_tags' => 'search#match_tags', :as => :multi_tag_search, :via => :get

  match 'static/:action' => 'static#:action', :as => :static, :via => :get

end

app/models/study.rb
class Study < ActiveRecord::Base
  include PgSearch

  pg_search_scope :search_all,
                  :against => [:code, :name, :description, :species, :benefits, :objectives, :organizations, :investigators, :funding],
                  :using => {
                    :tsearch => {:prefix => true},
                    :trigram => {}
                  },
                  :associated_against => {
                    :user =>  [ :name,
                                :organization,
                                :email
                              ]
                  }

  has_attached_file :img_first, :styles => { :medium => "360", :thumb => "75" }
  has_attached_file :img_second, :styles => { :medium => "360", :thumb => "75" }
  has_attached_file :img_third, :styles => { :medium => "360", :thumb => "75" }
  has_attached_file :img_fourth, :styles => { :medium => "360", :thumb => "75" }
  has_attached_file :img_fifth, :styles => { :medium => "360", :thumb => "75" }

  # Ability to remove images
  attr_accessor :delete_img_first, :delete_img_second, :delete_img_third, :delete_img_fourth, :delete_img_fifth
  before_validation(:on => :update) do
    img_first.clear if delete_img_first == '1'
    img_second.clear if delete_img_second == '1'
    img_third.clear if delete_img_third == '1'
    img_fourth.clear if delete_img_fourth == '1'
    img_fifth.clear if delete_img_fifth == '1'
  end

  belongs_to  :user
  validates   :user, :presence => true
  accepts_nested_attributes_for :user

  scope :active, where("title IS NOT NULL AND name IS NOT NULL AND start IS NOT NULL and ending IS NOT NULL")

  has_many    :deployments, :dependent => :destroy
  has_many    :tag_deployments, :dependent => :destroy
  has_many    :tags, :through => :tag_deployments, :dependent => :destroy

  def active
    Study.active.include?(self)
  end

  def organizations
    get_array(:organizations)
  end

  def organizations=(orgs)
    set_array(orgs, :organizations)
  end

  def objectives
    get_array(:objectives)
  end

  def objectives=(objs)
    set_array(objs, :objectives)
  end

  def funding
    get_array(:funding)
  end

  def funding=(funds)
    set_array(funds, :funding)
  end

  def benefits
    get_array(:benefits)
  end

  def benefits=(benefits)
    set_array(benefits, :benefits)
  end

  def investigators
    get_array(:investigators)
  end

  def investigators=(inves)
    set_array(inves, :investigators)
  end

  def get_array(sym)
    read_attribute(sym).split("=;=") rescue []
  end

  def set_array(setme, sym)
    if setme.is_a? String
      write_attribute(sym, setme)
    elsif setme.is_a? Array
      write_attribute(sym, setme.join("=;="))
    end
  end

  def self.clean_string(str)
    str.split(',',2)[-1].strip.chomp("\"").reverse.chomp("\"").reverse
  end

  def self.load_data(file)

    errors = []
    File.open(file) do |f|
      begin
        lines = f.readlines
        ENV['WEB_ADMIN_PASSWORD'] ||= "default"
        # Update or create a new PI user
        user_email = clean_string(lines[2]).downcase
        user = User.find_or_initialize_by_email(user_email)
        user.attributes =
          {
            :name => clean_string(lines[1])
          }

        # Set a password for a new user
        if user.new_record?
          user.attributes =
            {
              :password => ENV['WEB_ADMIN_PASSWORD'],
              :password_confirmation => ENV['WEB_ADMIN_PASSWORD'],
              :role => "investigator"
            }
        end
        unless user.valid?
          errors << "#{user.errors.full_messages.join(" and ")}"
        end

        code = clean_string(lines[0])
        study = Study.find_or_initialize_by_code(code)
        study.attributes =
          {
            :user => user
          }
        unless study.valid?
          errors << "#{study.errors.full_messages.join(" and ")}"
        end
      rescue Exception => e
        errors << "Error loading project: #{e}"
      end

      return user, study, errors

    end
  end

end
#
# == Schema Information
#
# Table name: studies
#
#  id                      :integer         not null, primary key
#  name                    :string(255)
#  description             :text
#  start                   :datetime
#  ending                  :datetime
#  url                     :string(255)
#  species                 :string(255)
#  user_id                 :integer
#  code                    :string(20)      not null
#  title                   :text
#  benefits                :text
#  organizations           :text
#  funding                 :text
#  information             :text
#  objectives              :text
#  investigators           :text
#  img_first_file_name     :string(255)
#  img_first_content_type  :string(255)
#  img_first_file_size     :integer
#  img_first_updated_at    :datetime
#  img_second_file_name    :string(255)
#  img_second_content_type :string(255)
#  img_second_file_size    :integer
#  img_second_updated_at   :datetime
#  img_third_file_name     :string(255)
#  img_third_content_type  :string(255)
#  img_third_file_size     :integer
#  img_third_updated_at    :datetime
#  img_fourth_file_name    :string(255)
#  img_fourth_content_type :string(255)
#  img_fourth_file_size    :integer
#  img_fourth_updated_at   :datetime
#  img_fifth_file_name     :string(255)
#  img_fifth_content_type  :string(255)
#  img_fifth_file_size     :integer
#  img_fifth_updated_at    :datetime
#

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  def index
    @studies = Study.active.order(:id)
    respond_to do |format|
      format.html
      format.json {
        render :json => @studies.as_json({

        })
      }
    end
  end

  def show
    @study = Study.includes(:user, :deployments, {:tag_deployments => :tag}).find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def edit
    @study = Study.includes(:user).find(params[:id])
    authorize! :update, @study
    respond_to do |format|
      format.html
    end
  end

  def update
    @study = Study.includes(:user).find(params[:id])
    authorize! :update, @study
    if @study.update_attributes(params[:study])
      flash[:notice] = 'Project was successfully updated.'
      redirect_to project_path(@study)
    else
      render :action => 'edit'
    end
  end

end

app/views/studies/edit.html.haml
#study_edit_page

  %h2 #{@study.name}

  - unless @study.active
    %h2 This project is INACTIVE
    The minimum amount of information required to show up on the website is: Name, Title, Start, and Ending
    %br

  = semantic_form_for(@study, :url => study_path(@study), :html => { :method => :put }) do |f|
    = f.inputs do
      = f.input :name, :hint => "Enter a short (45-character max.) title here"
      = f.input :title, :hint => "Enter full project title here"
      = f.input :description, :hint => "200 word max; suggest 1-2 paragraphs in non-technical language.  Include background or justification, fish information, tagging methods, receiver locations."
      = f.input :start, :as => :date, :start_year => Time.now.year - 30, :end_year => Time.now.year + 10, :hint => "Enter expected study start date here"
      = f.input :ending,:as => :date, :start_year => Time.now.year - 30, :end_year => Time.now.year + 10, :hint => "Enter expected study end date here"
      = f.input :url, :hint => "Enter an external URL where someone might go to get more information about the project"
      = f.input :species
      = f.input :code, :hint => "Unique 5-character code for project, preferably to represent study location and species.  Before changing this, please beware of the consequences!"
      = f.input :objectives, :hint => "List project objectives here, separated by the special string '=;='.  Each objective will then appear as a separate item in the list of objectives on your project page. For example, Learn migratory patterns=;=Establish seasonal baseline"
      = f.input :benefits, :hint => "List expected management benefits here.  This is REQUIRED for GLFC and GLRI-funded projects. Use the special string '=;=' to separate objectives if you'd like them presented in list format. If none, leave blank."
      = f.input :organizations, :hint => "List supporting and cooperating organizations here. Separate organizations with the special string '=;=' to present in list format."
      = f.input :funding, :hint => "List funding sources here. Separate funding sources with the special string '=;=' to present in list format."
      = f.input :investigators, :hint => "List other investigators here (organizations in parentheses). Separate investigators with the special string '=;=' to have them presented in list format on the project page."

      = f.semantic_fields_for :user do |u|
        = u.inputs do
          = u.input :name, :hint => "First and Last Name of Principal Investigator"
          = u.input :email, :hint => "Email of the Principal Investigator.  Warning: This will change the login of the PI."
          = u.input :organization, :hint => "Principal Investigator Affiliation"

      = f.input :img_first, :label => "First Image", :hint => "#{@study.img_first_file_name || 'None'}"
      - if @study.img_first.exists?
        = f.input :delete_img_first, :as => :boolean, :label => "Remove"
        = image_tag @study.img_first.url(:thumb)

      = f.input :img_second, :label => "Second Image", :hint => "#{@study.img_second_file_name || 'None'}"
      - if @study.img_second.exists?
        = f.input :delete_img_second, :as => :boolean, :label => "Remove"
        = image_tag @study.img_second.url(:thumb)

      = f.input :img_third, :label => "Third Image", :hint => "#{@study.img_third_file_name || 'None'}"
      - if @study.img_third.exists?
        = f.input :delete_img_third, :as => :boolean, :label => "Remove"
        = image_tag @study.img_third.url(:thumb)

      = f.input :img_fourth, :label => "Fourth Image", :hint => "#{@study.img_fourth_file_name || 'None'}"
      - if @study.img_fourth.exists?
        = f.input :delete_img_fourth, :as => :boolean, :label => "Remove"
        = image_tag @study.img_fourth.url(:thumb)

      = f.input :img_fifth, :label => "Fifth Image", :hint => "#{@study.img_fifth_file_name || 'None'}"
      - if @study.img_fifth.exists?
        = f.input :delete_img_fifth, :as => :boolean, :label => "Remove"
        = image_tag @study.img_fifth.url(:thumb)

    = f.actions do
      = f.action :submit, :as => :button, :label => "Update", :button_html => { :id => "Update"}

app/views/studies/show.html.haml
#study_page

  - if can? :update, @study
    = link_to "Edit this Project", edit_project_path(@study)

  %h2 #{@study.name}

  #listings
    .lineitem
      %span
        Project Title:
      #{@study.title}


    .lineitem
      %span
        GLATOS Project Code:
      #{@study.code}

    .lineitem
      %span
        Project Duration:
      #{@study.start.strftime("%B %Y") rescue nil} - #{@study.ending.strftime("%B %Y") rescue nil}

    .lineitem
      %span
        Project Description:
      #{@study.description}

    .lineitem
      %span
        Objectives:
      %ol
        - @study.objectives.each do |obj|
          %li
            #{obj}

    .lineitem
      %span
        Management Benefits:
      %ol
        - @study.benefits.each do |b|
          %li
            #{b}

    .lineitem
      %span
        Investigators:
      %ol
        %li
          = "#{@study.user.name} (#{@study.user.organization}) - #{@study.user.email}"
        - @study.investigators.each do |inv|
          %li
            #{inv}

    .lineitem
      %span
        Participating Organizations:
      %ol
        - @study.organizations.each do |org|
          %li
            #{org}

    .lineitem
      %span
        Funding:
      %ol
        - @study.funding.each do |fund|
          %li
            #{fund}

    .lineitem
      %span
        External URL:
      - if @study.url
        = link_to @study.url, @study.url

  #images
    = image_tag @study.img_first.url(:medium) if @study.img_first.exists?
    = image_tag @study.img_second.url(:medium) if @study.img_second.exists?
    = image_tag @study.img_third.url(:medium) if @study.img_third.exists?
    = image_tag @study.img_fourth.url(:medium) if @study.img_fourth.exists?
    = image_tag @study.img_fifth.url(:medium) if @study.img_fifth.exists?

  .clear