config/routes.rb
Glatos::Application.routes.draw do

  root :to => 'home#index'
  match '/about' => 'home#about', :as => :about, :via => :get
  match '/acoustic_telemetry' => 'home#acoustic_telemetry', :as => :acoustic_telemetry, :via => :get
  match '/have_data' => 'home#have_data', :as => :have_data, :via => :get

  devise_for :users

  resources :users, :only => [:index, :destroy, :update]
  match 'users/newsletter' => 'users#newsletter', :as => :user_newsletter, :via => :get

  resources :reports, :only => [:index, :new, :create, :destroy, :update, :show]

  resources :deployments, :only => [:index, :destroy]

  resources :submissions, :only => [:new, :create, :show, :index, :destroy] do
    member do
      get 'analyze'
      get 'parse'
      get 'deployments'
      get 'proposed'
      get 'retrievals'
      get 'tags'
      get 'locations'
      get 'project'
    end
  end

  # The projects controller is identical to the studies
  resources :studies, :projects, :controller => :studies, :only => [:index, :show, :edit, :update] do
    resources :deployments, :only => [:index, :destroy]
    resources :reports, :only => [:index, :destroy, :update]
  end

  match 'explore' => 'explore#index', :as => :explore, :via => :get
  match 'search' => 'search#index', :as => :search, :via => :get
  match 'search/tags' => 'search#tags', :as => :search_tags, :via => :get
  match 'search/reports' => 'search#reports', :as => :search_reports, :via => :get
  match 'search/studies' => 'search#studies', :as => :search_studies, :via => :get
  match 'search/deployments' => 'search#deployments', :as => :search_deployments, :via => :get
  match 'search/tag' => 'search#tag', :as => :tag_search, :via => :get
  match 'search/match_tags' => 'search#match_tags', :as => :multi_tag_search, :via => :get

  match 'static/:action' => 'static#:action', :as => :static, :via => :get

end

app/models/submission.rb
class Submission < ActiveRecord::Base

  belongs_to :user

  before_destroy :destroy_extracted

  has_attached_file :zipfile, {
    :url => "#{ActionController::Base.relative_url_root}/system/:class/:attachment/:id/:style/:basename.:extension",
    :path => "public/system/:class/:attachment/:id/:style/:basename.:extension"
  }

  validates_presence_of :user

  validates_attachment_presence :zipfile
  validates_attachment_content_type :zipfile, :content_type => /^application\/(x-zip-compressed|zip)$/, :message => 'is not a ZIP file'

  def DT_RowId
    self.id
  end

  def zipfile_url
    self.zipfile.url
  end

  def status=(status)
    write_attribute(:status,status.downcase)
  end

  def extract
    Zip::ZipFile.open(self.zipfile.path) do |zip|
      zip.each do |entry|
        zip.extract(entry, "#{File.dirname(self.zipfile.path)}/#{entry.name}")
      end
    end

  end

  def destroy_extracted
    FileUtils.rm_f(self.csvfiles)
    FileUtils.rm_f(self.xlsmfiles)
  end

  def csvfiles
    return Dir[File.dirname(Rails.root + self.zipfile.path) + "/*.csv"]
  end

  def xlsmfiles
    return Dir[File.dirname(Rails.root + self.zipfile.path) + "/*.xlsm"]
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  layout 'submission'

  def index
    authorize! :manage, Submission
    respond_to do |format|
      format.html { render :layout => 'admin' }
      format.dataTable {
        columns = params[:sColumns].split(",")
        sort_direction = params[:sSortDir_0]
        sort_column = columns[params[:iSortCol_0].to_i].to_s
        page_num = (params[:iDisplayStart].to_i / params[:iDisplayLength].to_i) + 1

        submissions = Submission.includes(:user).order("#{sort_column} #{sort_direction}").page(page_num.to_i).per(params[:iDisplayLength].to_i)
        render :json => {
          :sEcho => params[:sEcho],
          :iTotalRecords => submissions.total_count,
          :iTotalDisplayRecords => submissions.total_count,
          :aaData => submissions.as_json({
            :methods => [:DT_RowId, :zipfile_url],
            :only => [:status],
            :include => {:user => {
                          :only => [:name, :email]
                        }}
          })
        }
      }
    end
  end

  def new
    authorize! :create, Submission
    @submission = Submission.new
  end

  def create
    authorize! :create, Submission
    @submission = Submission.new( params[:submission] )
    @submission.user = current_user
    @submission.status = "New"
    if @submission.save
      redirect_to submission_path(@submission), :notice => "Submission was successfully uploaded.  You will recieve an email when your project data is ready for editing."
    else
      render :action => :new
    end
  end

  def show
    @submission = Submission.includes(:user).find(params[:id])
    authorize! :read, @submission
    respond_to do |format|
      format.html
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    authorize! :destroy, @submission
    @submission.destroy
    respond_to do |format|
      format.html
      format.js { render :json => nil, :status => :ok}
    end
  end

  def analyze
    @submission = Submission.find(params[:id])
    @submission.extract
    authorize! :manage, @submission
    respond_to do |format|
      format.html
    end
  end

  def parse
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    csvfiles = @submission.csvfiles
    # Project
    user,study,errors = Study.load_data(csvfiles.grep(/project/i).first)
    respond_to do |format|
      format.js { render :json => {:errors => errors, :study => study, :user => user} }
    end
  end

  def project
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    authorize! :create, Study
    authorize! :create, User
    csvfiles = @submission.csvfiles
    # Save Project
    user,study,errors = Study.load_data(csvfiles.grep(/project/i).first)
    user.save
    study.save
    study.deployments.destroy_all
    study.tags.destroy_all
    respond_to do |format|
      format.js { render :json => {:errors => errors} }
    end
  end

  def locations
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    csvfiles = @submission.csvfiles
    # OTN_ARRAY
    otns,errors,count = OtnArray.load_data(csvfiles.grep(/location/i).first)
    otns.map(&:save)
    respond_to do |format|
      format.js { render :json => {:errors => errors, :total => count, :saved => otns.size} }
    end
  end

  def deployments
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    # DEPLOYMENTS
    csvfiles = @submission.csvfiles
    deps,errors,count = Deployment.load_data(csvfiles.grep(/deployment/i).first)
    deps.each(&:save)
    respond_to do |format|
      format.js { render :json => {:errors => errors, :total => count, :saved => deps.size} }
    end
  end

  def proposed
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    # PROPOSED DEPLOYMENTS
    csvfiles = @submission.csvfiles
    props,errors,count = Deployment.load_proposed_data(csvfiles.grep(/proposed/i).first)
    props.each(&:save!)
    respond_to do |format|
      format.js { render :json => {:errors => errors, :total => count, :saved => props.size} }
    end
  end

  def retrievals
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    # RETRIEVALS
    csvfiles = @submission.csvfiles
    rets,errors,count = Retrieval.load_data(csvfiles.grep(/recover/i).first)
    rets.each(&:save)
    respond_to do |format|
      format.js { render :json => {:errors => errors, :total => count, :saved => rets.size} }
    end
  end

  def tags
    @submission = Submission.find(params[:id])
    authorize! :manage, @submission
    # TAGS
    csvfiles = @submission.csvfiles
    tags,tagerrors,count1 = Tag.load_data(csvfiles.grep(/tagging/i).first)
    tags.each(&:save)

    # TAG DEPLOYMENTS
    tagdeps,tagdeperrors,count2 = Tag.load_tag_deployments(csvfiles.grep(/tagging/i).first)
    tagdeps.each(&:save)

    respond_to do |format|
      format.js { render :json => {:errors => tagerrors + tagdeperrors, :total => count1, :saved => tags.size} }
    end
  end

end

app/views/submissions/analyze.html.haml
#analyze_submission

  - if @submission

    %strong
      #{@submission.zipfile_file_name}

    (
    = link_to "Download", @submission.zipfile.url
    )

    %br
    %br

    %button{:id => 'analyze'}
      Analyze Submission

    %button{:id => 'process'}
      Process Submission - All project data will be replaced!

    %br
    %br

    #messages

    %br
    %br

    #project_info

    %br
    %br

    #accordion
      %h3{:id => 'project_h'}
        = image_tag('spinner-small.gif', :id => 'projspin', :style => 'display: none;')
        %a{:href => "#"}
          Project
      #project

      %h3
        = image_tag('spinner-small.gif', :id => 'locspin', :style => 'display: none;')
        %a{:href => "#"}
          Locations
      #locations

      %h3
        = image_tag('spinner-small.gif', :id => 'depspin', :style => 'display: none;')
        %a{:href => "#"}
          Deployment
      #deployments

      %h3
        = image_tag('spinner-small.gif', :id => 'propspin', :style => 'display: none;')
        %a{:href => "#"}
          Proposed
      #proposed

      %h3
        = image_tag('spinner-small.gif', :id => 'retspin', :style => 'display: none;')
        %a{:href => "#"}
          Retrievals
      #retrievals

      %h3
        = image_tag('spinner-small.gif', :id => 'tagspin', :style => 'display: none;')
        %a{:href => "#"}
          Tags
      #tags


  %div{:style => "height: 400px;"}


:javascript

  $(document).ready(function() {

    $( "#accordion" ).maccordion({active: false});
    $("#process").attr('disabled', true);
    $("#analyze").removeAttr('disabled');

    function call_locations() {
      $("#locspin").show();
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{locations_submission_path(@submission)}.js",
        success: function(x) {
          append_results("#locations", x);
          $( "#accordion" ).maccordion("refresh");
          call_deployments();
        },
        error: function(x) {
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#locspin").hide();
        }
      });
    }

    function call_deployments() {
      $("#depspin").show();
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{deployments_submission_path(@submission)}.js",
        success: function(x) {
          append_results("#deployments", x);
          $( "#accordion" ).maccordion("refresh");
          call_proposed();
        },
        error: function(x) {
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#depspin").hide();
        }
      });
    }

    function call_proposed() {
      $("#propspin").show();
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{proposed_submission_path(@submission)}.js",
        success: function(x) {
          append_results("#proposed", x);
          $( "#accordion" ).maccordion("refresh");
          call_retrievals();
        },
        error: function(x) {
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#propspin").hide();
        }
      });
    }

    function call_retrievals() {
      $("#retspin").show();
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{retrievals_submission_path(@submission)}.js",
        success: function(x) {
          append_results("#retrievals", x);
          $( "#accordion" ).maccordion("refresh");
          call_tags();
        },
        error: function(x) {
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#retspin").hide();
        }
      });
    }

    function call_tags() {
      $("#tagspin").show();
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{tags_submission_path(@submission)}.js",
        success: function(x) {
          append_results("#tags", x);
          $( "#accordion" ).maccordion("refresh");
        },
        error: function(x){
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#tagspin").hide();
          $("#messages").html("<div class='info'>Submission Complete.  Please check for information about individual data sheets below.</div>")
        }
      });
    }

    function append_results(div_string, results) {

      clear_results(div_string);

      if (results.total != null) {
        fstring  = "<table class='subtable'>";
        fstring += "<tr><td class='label'>Records in File</td><td>"+results.total+"</td></tr>";
        fstring += "</table>";
        $(div_string).append(fstring);
      }
      if (results.saved != null) {
        fstring  = "<table class='subtable'>";
        fstring += "<tr><td class='label'>Records Saved</td><td>"+results.saved+"</td></tr>";
        fstring += "</table>";
        $(div_string).append(fstring);
      }
      if (results.errors != null) {
        fstring  = "<table class='subtable'>";
        fstring += "<tr><td class='label'>Errors</td><td>"+results.errors.length+"</td></tr>";
        fstring += "</table>";
        $(div_string).append(fstring);

        error_string  = "<table class='subtable'>";
        $.each(results.errors, function(i,e) {
          error_string += "<tr><td>" + e + "</td><td /></tr>"
        });
        error_string += "</table>";
        $(div_string).append(error_string);
      }

      if (results.study != null) {
        study_string = "<table class='subtable'>";
        study_string += "<tr><td class='label'>Project</td><td /></tr>";
        study_string += "<tr><td class='label'>Code</td><td>" + results.study.code + "</td></tr>";
        study_string += "<tr><td class='label'>Short Title</td><td>" + results.study.name + "</td></tr>";
        study_string += "<tr><td class='label'>Title</td><td>" + results.study.title + "</td></tr>";
        study_string += "<tr><td class='label'>Description</td><td>" + results.study.description + "</td></tr>";
        study_string += "<tr><td class='label'>Start</td><td>" + results.study.start + "</td></tr>";
        study_string += "<tr><td class='label'>End</td><td>" + results.study.ending + "</td></tr>";
        study_string += "<tr><td class='label'>External URL</td><td>" + results.study.url + "</td></tr>";

        $.each(results.study.benefits, function(i,e) {
          study_string += "<tr><td class='label'>Benefit " + i + ":</td><td>" + e + "</td></tr>";
        });
        $.each(results.study.funding, function(i,e) {
          study_string += "<tr><td class='label'>Funding Source " + i + ":</td><td>" + e + "</td></tr>";
        });
        $.each(results.study.investigators, function(i,e) {
          study_string += "<tr><td class='label'>Investigator " + i + ":</td><td>" + e + "</td></tr>";
        });
        $.each(results.study.objectives, function(i,e) {
          study_string += "<tr><td class='label'>Objective " + i + ":</td><td>" + e + "</td></tr>";
        });
        $.each(results.study.organizations, function(i,e) {
          study_string += "<tr><td class='label'>Organization " + i + ":</td><td>" + e + "</td></tr>";
        });
        study_string += "</table>";
        $(div_string).append(study_string);
      }

      if (results.user != null) {
        user_string = "<table class='subtable'>";
        user_string += "<tr><td class='label'>PI</td><td /></tr>";
        user_string += "<tr><td class='label'>Name</td><td>" + results.user.name + "</td></tr>";
        user_string += "<tr><td class='label'>Email</td><td>" + results.user.email + "</td></tr>";
        user_string += "<tr><td class='label'>Organization</td><td>" + results.user.organization + "</td></tr>";
        user_string += "<tr><td class='label'>Role</td><td>" + results.user.role + "</td></tr>";
        user_string += "</table>";
        $(div_string).append(user_string);
      }

    }

    function clear_results(div_string) {
      $(div_string).html("");
    }

    $("#process").click(function(e) {
      $("#projspin").show();
      e.preventDefault();
      $("#process").attr('disabled', true);
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{project_submission_path(@submission)}.js",
        success: function(x) {

          append_results("#project", x);
          $( "#accordion" ).maccordion("refresh");
          call_locations();
        },
        error: function(x) {
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#projspin").hide();
        }
      });
    });

    $("#analyze").click(function(e) {
      $("#projspin").show();
      e.preventDefault();
      clear_results("#project");
      clear_results("#locations");
      clear_results("#deployments");
      clear_results("#proposed");
      clear_results("#retrievals");
      clear_results("#tags");
      $( "#accordion" ).maccordion("refresh");
      $.ajax({
        type: "GET",
        dataType: "json",
        url: "#{parse_submission_path(@submission)}.js",
        success: function(x) {
          if (x.errors.length == 0) {
            delete x.errors
            $("#process").removeAttr("disabled");
            $("#analyze").attr('disabled', true);
            $("#messages").html("<div class='info'>Please double check the Project and PI information below before submitting.</div>")
          } else {
            delete x.study
            delete x.user
            $("#messages").html("<div class='error'>Errors found in project data.  Please update project information in the Zipfile and try again.  Details below.</div>")
          }
          append_results("#project_info", x);
        },
        error: function(x) {
          alert('Failed to parse ' + x);
        },
        complete: function() {
          $("#projspin").hide();
        }
      });
    });
  });

app/views/submissions/index.html.haml
%h1 Submissions

%table{:id => :table}

  :javascript

    function makeActionButtons(oObj) {
      var text = "";
      text += "<a href='#' class='destroyer'>Delete</a> ";
      text += "<a href='#{submissions_path}/" + oObj.aData.DT_RowId + "/analyze' class='analyzer'>Analyze</a> ";
      return text;
    }

    function makeLink(oObj) {
      var text = "";
      text += "<a href='" + oObj.aData.zipfile_url + "' class='linker'>View</a>";
      return text;
    }

    var oTable;

    $(document).ready(function() {

      /* Init DataTables */
      oTable = $('#table').dataTable( {
        "bJQueryUI": true,
        "bProcessing": true,
        "bServerSide": true,
        "bDeferRender": true,
        "bFilter": false,
        "sPaginationType": "full_numbers",
        "sAjaxSource": "#{submissions_path({:format => :dataTable})}",
        "aoColumns": [
          { "sTitle": "Status", "sName": "status", "mDataProp": "status" },
          { "sTitle": "Name", "sName": "user.name", "mDataProp": "user.name", "bSortable": false },
          { "sTitle": "Email", "sName": "user.email", "mDataProp": "user.email", "bSortable": false },
          { "sTitle": "Zipfile", "sName": "zipfile_url", "mDataProp": "zipfile_url", "bSortable": false, "fnRender": function (oObj){ return makeLink(oObj); }  },
          { "sTitle": "Actions", "sName": "action", "mDataProp": null, "bSortable": false, "fnRender": function (oObj){ return makeActionButtons(oObj); } }
        ],
        "fnDrawCallback": function(oSettings, json) {

          $(".destroyer").click(function(e) {
            if(confirm("Are you sure you want to DELETE?")) {
              e.preventDefault();
              var aData = oTable.fnGetData($(this).parents('tr')[0]);
              var id = aData.DT_RowId;
              $.ajax({
                type: "DELETE",
                url: "#{submissions_path}/"+id+".js",
                success: function(){
                  oTable.fnDraw();
                },
                error: function(){
                  alert('Failed to delete Submission');
                }
              });
            }
          });
        }
      });
    });

app/views/submissions/new.html.haml
%p
  The uploaded file should have the extension
  %strong
    zip
  and be the result of clicking on the
  %strong
    Create Submission Package
  button in
  %strong
    GLATOSWeb_DataForms.xlsm.

= semantic_form_for @submission, :html => { :multipart => true }, :url => submissions_path do |f|
  = f.input :zipfile, :as => :file, :label => false
  = f.actions do
    = f.action :submit, :as => :button, :label => "Upload"

app/views/submissions/show.html.haml
#show_report

  - if @submission

    %p Here is information about the data submission

    %table
      %tbody
        %tr
          %td{:class => "label"}
            Name
          %td
            = @submission.user.name
        %tr
          %td{:class => "label"}
            Email
          %td
            = @submission.user.email
        %tr
          %td{:class => "label"}
            Zipfile
          %td
            = link_to "Download", "#{request.protocol}#{request.host_with_port}#{@submission.zipfile.url}"
        %tr
          %td{:class => "label"}
            Status
          %td
            = @submission.status.humanize
        %tr
          %td{:class => "label"}
            Uploaded
          %td
            = @submission.created_at.in_time_zone
    .clear

  - if can? :manage, @submission
    %br
    = link_to "Analyze Submission", analyze_submission_path(@submission)


  %div{:style => "height: 400px;"}